version: "3.9"

services:
  tgmoji:
    build: .
    image: ghcr.io/yesbhautik/tgmoji:latest
    container_name: tgmoji
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost/" ]
      interval: 30s
      timeout: 3s
      retries: 3
